config/routes.rb
Rails.application.routes.draw do
  resources :goal_triggers
  resources :weeklogs
  resources :incentives
  resources :daylogs
  resources :rules
  resources :demerits
  resources :metrics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/demerit.rb
class Demerit < ApplicationRecord
  validates :name, uniqueness: true

  has_many :demerit_logs
end

app/controllers/demerits_controller.rb
class DemeritsController < ApplicationController
  before_action :set_demerit, only: [:show, :edit, :update, :destroy]

  # GET /demerits
  # GET /demerits.json
  def index
    @demerits = Demerit.all
  end

  # GET /demerits/1
  # GET /demerits/1.json
  def show
  end

  # GET /demerits/new
  def new
    @demerit = Demerit.new
  end

  # GET /demerits/1/edit
  def edit
  end

  # POST /demerits
  # POST /demerits.json
  def create
    @demerit = Demerit.new(demerit_params)

    respond_to do |format|
      if @demerit.save
        format.html { redirect_to @demerit, notice: 'Demerit was successfully created.' }
        format.json { render :show, status: :created, location: @demerit }
      else
        format.html { render :new }
        format.json { render json: @demerit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demerits/1
  # PATCH/PUT /demerits/1.json
  def update
    respond_to do |format|
      if @demerit.update(demerit_params)
        format.html { redirect_to @demerit, notice: 'Demerit was successfully updated.' }
        format.json { render :show, status: :ok, location: @demerit }
      else
        format.html { render :edit }
        format.json { render json: @demerit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demerits/1
  # DELETE /demerits/1.json
  def destroy
    @demerit.destroy
    respond_to do |format|
      format.html { redirect_to demerits_url, notice: 'Demerit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demerit
      @demerit = Demerit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demerit_params
      params.require(:demerit).permit(:name)
    end
end

app/helpers/demerits_helper.rb
module DemeritsHelper
end

app/views/demerits/_form.html.erb
<%= form_with(model: demerit, local: true) do |form| %>
  <% if demerit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(demerit.errors.count, "error") %> prohibited this demerit from being saved:</h2>

      <ul>
      <% demerit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :demerit_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/demerits/edit.html.erb
<h1>Editing Demerit</h1>

<%= render 'form', demerit: @demerit %>

<%= link_to 'Show', @demerit %> |
<%= link_to 'Back', demerits_path %>

app/views/demerits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Demerits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @demerits.each do |demerit| %>
      <tr>
        <td><%= demerit.name %></td>
        <td><%= link_to 'Show', demerit %></td>
        <td><%= link_to 'Edit', edit_demerit_path(demerit) %></td>
        <td><%= link_to 'Destroy', demerit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Demerit', new_demerit_path %>

app/views/demerits/new.html.erb
<h1>New Demerit</h1>

<%= render 'form', demerit: @demerit %>

<%= link_to 'Back', demerits_path %>

app/views/demerits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @demerit.name %>
</p>

<%= link_to 'Edit', edit_demerit_path(@demerit) %> |
<%= link_to 'Back', demerits_path %>