config/routes.rb
Rails.application.routes.draw do
  resources :goal_triggers
  resources :weeklogs
  resources :incentives
  resources :daylogs
  resources :rules
  resources :demerits
  resources :metrics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/weeklog.rb
class Weeklog < ApplicationRecord
end

app/controllers/weeklogs_controller.rb
class WeeklogsController < ApplicationController
  before_action :set_weeklog, only: [:show, :edit, :update, :destroy]

  # GET /weeklogs
  # GET /weeklogs.json
  def index
    @weeklogs = Weeklog.all
  end

  # GET /weeklogs/1
  # GET /weeklogs/1.json
  def show
  end

  # GET /weeklogs/new
  def new
    @weeklog = Weeklog.new
  end

  # GET /weeklogs/1/edit
  def edit
  end

  # POST /weeklogs
  # POST /weeklogs.json
  def create
    @weeklog = Weeklog.new(weeklog_params)

    respond_to do |format|
      if @weeklog.save
        format.html { redirect_to @weeklog, notice: 'Weeklog was successfully created.' }
        format.json { render :show, status: :created, location: @weeklog }
      else
        format.html { render :new }
        format.json { render json: @weeklog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weeklogs/1
  # PATCH/PUT /weeklogs/1.json
  def update
    respond_to do |format|
      if @weeklog.update(weeklog_params)
        format.html { redirect_to @weeklog, notice: 'Weeklog was successfully updated.' }
        format.json { render :show, status: :ok, location: @weeklog }
      else
        format.html { render :edit }
        format.json { render json: @weeklog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weeklogs/1
  # DELETE /weeklogs/1.json
  def destroy
    @weeklog.destroy
    respond_to do |format|
      format.html { redirect_to weeklogs_url, notice: 'Weeklog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weeklog
      @weeklog = Weeklog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weeklog_params
      params.require(:weeklog).permit(:start_date_code, :end_date_code, :weekly_incentive, :incentive_total, :wins, :losses)
    end
end

app/helpers/weeklogs_helper.rb
module WeeklogsHelper
end

app/views/weeklogs/_form.html.erb
<%= form_with(model: weeklog, local: true) do |form| %>
  <% if weeklog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weeklog.errors.count, "error") %> prohibited this weeklog from being saved:</h2>

      <ul>
      <% weeklog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date_code %>
    <%= form.number_field :start_date_code, id: :weeklog_start_date_code %>
  </div>

  <div class="field">
    <%= form.label :end_date_code %>
    <%= form.number_field :end_date_code, id: :weeklog_end_date_code %>
  </div>

  <div class="field">
    <%= form.label :weekly_incentive %>
    <%= form.number_field :weekly_incentive, id: :weeklog_weekly_incentive %>
  </div>

  <div class="field">
    <%= form.label :incentive_total %>
    <%= form.number_field :incentive_total, id: :weeklog_incentive_total %>
  </div>

  <div class="field">
    <%= form.label :wins %>
    <%= form.number_field :wins, id: :weeklog_wins %>
  </div>

  <div class="field">
    <%= form.label :losses %>
    <%= form.number_field :losses, id: :weeklog_losses %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/weeklogs/edit.html.erb
<h1>Editing Weeklog</h1>

<%= render 'form', weeklog: @weeklog %>

<%= link_to 'Show', @weeklog %> |
<%= link_to 'Back', weeklogs_path %>

app/views/weeklogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Weeklogs</h1>

<table>
  <thead>
    <tr>
      <th>Start date code</th>
      <th>End date code</th>
      <th>Weekly incentive</th>
      <th>Incentive total</th>
      <th>Wins</th>
      <th>Losses</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weeklogs.each do |weeklog| %>
      <tr>
        <td><%= weeklog.start_date_code %></td>
        <td><%= weeklog.end_date_code %></td>
        <td><%= weeklog.weekly_incentive %></td>
        <td><%= weeklog.incentive_total %></td>
        <td><%= weeklog.wins %></td>
        <td><%= weeklog.losses %></td>
        <td><%= link_to 'Show', weeklog %></td>
        <td><%= link_to 'Edit', edit_weeklog_path(weeklog) %></td>
        <td><%= link_to 'Destroy', weeklog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weeklog', new_weeklog_path %>

app/views/weeklogs/new.html.erb
<h1>New Weeklog</h1>

<%= render 'form', weeklog: @weeklog %>

<%= link_to 'Back', weeklogs_path %>

app/views/weeklogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date code:</strong>
  <%= @weeklog.start_date_code %>
</p>

<p>
  <strong>End date code:</strong>
  <%= @weeklog.end_date_code %>
</p>

<p>
  <strong>Weekly incentive:</strong>
  <%= @weeklog.weekly_incentive %>
</p>

<p>
  <strong>Incentive total:</strong>
  <%= @weeklog.incentive_total %>
</p>

<p>
  <strong>Wins:</strong>
  <%= @weeklog.wins %>
</p>

<p>
  <strong>Losses:</strong>
  <%= @weeklog.losses %>
</p>

<%= link_to 'Edit', edit_weeklog_path(@weeklog) %> |
<%= link_to 'Back', weeklogs_path %>