config/routes.rb
Rails.application.routes.draw do
  resources :goal_triggers
  resources :weeklogs
  resources :incentives
  resources :daylogs
  resources :rules
  resources :demerits
  resources :metrics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/goal_trigger.rb
class GoalTrigger < ApplicationRecord
  belongs_to :metric

  validates :trigger_level, numericality: {greater_than: 0, less_than: 5}

  FREQUENCY_TYPE = {
    'd' => :daily,
    'w' => :weekly,
    'm' => :monthly
  }
end

app/controllers/goal_triggers_controller.rb
class GoalTriggersController < ApplicationController
  before_action :set_goal_trigger, only: [:show, :edit, :update, :destroy]

  # GET /goal_triggers
  # GET /goal_triggers.json
  def index
    @goal_triggers = GoalTrigger.all
  end

  # GET /goal_triggers/1
  # GET /goal_triggers/1.json
  def show
  end

  # GET /goal_triggers/new
  def new
    @goal_trigger = GoalTrigger.new
  end

  # GET /goal_triggers/1/edit
  def edit
  end

  # POST /goal_triggers
  # POST /goal_triggers.json
  def create
    @goal_trigger = GoalTrigger.new(goal_trigger_params)

    respond_to do |format|
      if @goal_trigger.save
        format.html { redirect_to @goal_trigger, notice: 'Goal trigger was successfully created.' }
        format.json { render :show, status: :created, location: @goal_trigger }
      else
        format.html { render :new }
        format.json { render json: @goal_trigger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goal_triggers/1
  # PATCH/PUT /goal_triggers/1.json
  def update
    respond_to do |format|
      if @goal_trigger.update(goal_trigger_params)
        format.html { redirect_to @goal_trigger, notice: 'Goal trigger was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal_trigger }
      else
        format.html { render :edit }
        format.json { render json: @goal_trigger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goal_triggers/1
  # DELETE /goal_triggers/1.json
  def destroy
    @goal_trigger.destroy
    respond_to do |format|
      format.html { redirect_to goal_triggers_url, notice: 'Goal trigger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal_trigger
      @goal_trigger = GoalTrigger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_trigger_params
      params.require(:goal_trigger).permit(:frequency, :metric_id, :trigger_level, :spoils, :fee, :message)
    end
end

app/helpers/goal_triggers_helper.rb
module GoalTriggersHelper
end

app/views/goal_triggers/_form.html.erb
<%= form_with(model: goal_trigger, local: true) do |form| %>
  <% if goal_trigger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal_trigger.errors.count, "error") %> prohibited this goal_trigger from being saved:</h2>

      <ul>
      <% goal_trigger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :frequency %>
    <%= form.text_field :frequency, id: :goal_trigger_frequency %>
  </div>

  <div class="field">
    <%= form.label :metric_id %>
    <%= form.text_field :metric_id, id: :goal_trigger_metric_id %>
  </div>

  <div class="field">
    <%= form.label :trigger_level %>
    <%= form.number_field :trigger_level, id: :goal_trigger_trigger_level %>
  </div>

  <div class="field">
    <%= form.label :spoils %>
    <%= form.number_field :spoils, id: :goal_trigger_spoils %>
  </div>

  <div class="field">
    <%= form.label :fee %>
    <%= form.number_field :fee, id: :goal_trigger_fee %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message, id: :goal_trigger_message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goal_triggers/edit.html.erb
<h1>Editing Goal Trigger</h1>

<%= render 'form', goal_trigger: @goal_trigger %>

<%= link_to 'Show', @goal_trigger %> |
<%= link_to 'Back', goal_triggers_path %>

app/views/goal_triggers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goal Triggers</h1>

<table>
  <thead>
    <tr>
      <th>Frequency</th>
      <th>Metric</th>
      <th>Trigger level</th>
      <th>Spoils</th>
      <th>Fee</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goal_triggers.each do |goal_trigger| %>
      <tr>
        <td><%= goal_trigger.frequency %></td>
        <td><%= goal_trigger.metric %></td>
        <td><%= goal_trigger.trigger_level %></td>
        <td><%= goal_trigger.spoils %></td>
        <td><%= goal_trigger.fee %></td>
        <td><%= goal_trigger.message %></td>
        <td><%= link_to 'Show', goal_trigger %></td>
        <td><%= link_to 'Edit', edit_goal_trigger_path(goal_trigger) %></td>
        <td><%= link_to 'Destroy', goal_trigger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal Trigger', new_goal_trigger_path %>

app/views/goal_triggers/new.html.erb
<h1>New Goal Trigger</h1>

<%= render 'form', goal_trigger: @goal_trigger %>

<%= link_to 'Back', goal_triggers_path %>

app/views/goal_triggers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frequency:</strong>
  <%= @goal_trigger.frequency %>
</p>

<p>
  <strong>Metric:</strong>
  <%= @goal_trigger.metric %>
</p>

<p>
  <strong>Trigger level:</strong>
  <%= @goal_trigger.trigger_level %>
</p>

<p>
  <strong>Spoils:</strong>
  <%= @goal_trigger.spoils %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @goal_trigger.fee %>
</p>

<p>
  <strong>Message:</strong>
  <%= @goal_trigger.message %>
</p>

<%= link_to 'Edit', edit_goal_trigger_path(@goal_trigger) %> |
<%= link_to 'Back', goal_triggers_path %>